FROM darthjee/stalchild-base:0.0.1

WORKDIR /home/app/app
COPY --chown=app:app source/Gemfile* /home/app/app/
COPY --chown=app:app source/package.json /home/app/app/

RUN bundle install
RUN yarn install
